# ================================
# SERVER CONFIG
# ================================
server.port=8080
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
# ================================
# APPLICATION NAME
# ================================
spring.application.name=api-gateway

# ================================
# EUREKA CONFIG
# ================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ================================
# GATEWAY ROUTES
# ================================
# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# CONVERTER SERVICE
spring.cloud.gateway.routes[1].id=converter-service
spring.cloud.gateway.routes[1].uri=lb://CONVERTER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/convert/**

# COMPARISON SERVICE
spring.cloud.gateway.routes[2].id=comparison-service
spring.cloud.gateway.routes[2].uri=lb://COMPARISON-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/compare/**

#Arithmetic Service
spring.cloud.gateway.routes[3].id=arithmetic-service
spring.cloud.gateway.routes[3].uri=lb://ARITHMETIC-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/measurements/**

# OAUTH2 ROUTES
spring.cloud.gateway.routes[4].id=user-service-oauth-init
spring.cloud.gateway.routes[4].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/oauth2/authorization/**

spring.cloud.gateway.routes[5].id=user-service-oauth-callback
spring.cloud.gateway.routes[5].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/login/oauth2/**
